"""add_playstyles

Revision ID: 1c7d8e9f2a1b
Revises: eca6cd6f4903
Create Date: 2026-06-04 23:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c7d8e9f2a1b'
down_revision: Union[str, None] = 'eca6cd6f4903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('grl_score', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('playstyles_defence', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('playstyles_midfield', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('playstyles_forwards', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=True)

    op.add_column('teams', sa.Column('playstyles_defence', postgresql.ARRAY(sa.Text()), nullable=False, server_default='{}'))
    op.add_column('teams', sa.Column('playstyles_midfield', postgresql.ARRAY(sa.Text()), nullable=False, server_default='{}'))
    op.add_column('teams', sa.Column('playstyles_forwards', postgresql.ARRAY(sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'playstyles_forwards')
    op.drop_column('teams', 'playstyles_midfield')
    op.drop_column('teams', 'playstyles_defence')

    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###

